[package]
name = "search-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tiny_http = "0.12.0"
urlencoding = "2.1.3"
xml-rs = "1.0.0"
rayon = "1.10.0"
